import { ThemeConfig, ThemeId } from '../types';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  onyx_minimal: {
    id: 'onyx_minimal',
    name: 'Onyx Studio (Signature)',
    tagline: 'Deep black & shadow grey with sunset orange accent',
    isMonochrome: true,
    isPastel: false,
    previewBg: '#000001',
    previewAccent: '#F85E2B',
    backgroundLight: 'bg-[#ECECED]',
    backgroundDark: 'bg-[#000001]',
    cardLight: 'bg-white',
    cardDark: 'bg-[#141415]',
    borderLight: 'border-zinc-200',
    borderDark: 'border-[#16161C]',
    accentLight: 'bg-[#F85E2B] text-white hover:bg-[#e04f1f]',
    accentDark: 'bg-[#F85E2B] text-white hover:bg-[#ff6c3b]',
    textLight: 'text-[#000001]',
    textDark: 'text-[#C7C6C9]',
    mutedLight: 'text-zinc-500',
    mutedDark: 'text-[#646366]',
    glowColor: 'rgba(248, 94, 43, 0.25)',
    highlightCardBg: '#F85E2B',
  },
  studio_light: {
    id: 'studio_light',
    name: 'Studio Minimal Light',
    tagline: 'Clean warm chalk backdrop with vibrant highlight cards',
    isMonochrome: false,
    isPastel: false,
    previewBg: '#F3F3F5',
    previewAccent: '#F85E2B',
    backgroundLight: 'bg-[#F0F0F3]',
    backgroundDark: 'bg-[#000001]',
    cardLight: 'bg-white shadow-xs',
    cardDark: 'bg-[#141415]',
    borderLight: 'border-zinc-200/70',
    borderDark: 'border-[#16161C]',
    accentLight: 'bg-[#F85E2B] text-white hover:bg-[#e04f1f]',
    accentDark: 'bg-[#F85E2B] text-white hover:bg-[#ff6c3b]',
    textLight: 'text-[#141415]',
    textDark: 'text-[#C7C6C9]',
    mutedLight: 'text-[#646366]',
    mutedDark: 'text-[#646366]',
    glowColor: 'rgba(248, 94, 43, 0.2)',
    highlightCardBg: '#F85E2B',
  },
  monochrome: {
    id: 'monochrome',
    name: 'Noir & White',
    tagline: 'Pure maternal minimalism in stark black & white',
    isMonochrome: true,
    isPastel: false,
    previewBg: '#ffffff',
    previewAccent: '#18181b',
    backgroundLight: 'bg-zinc-50',
    backgroundDark: 'bg-zinc-950',
    cardLight: 'bg-white',
    cardDark: 'bg-zinc-900',
    borderLight: 'border-zinc-200',
    borderDark: 'border-zinc-800',
    accentLight: 'bg-zinc-900 text-white hover:bg-zinc-800',
    accentDark: 'bg-white text-zinc-950 hover:bg-zinc-100',
    textLight: 'text-zinc-900',
    textDark: 'text-zinc-100',
    mutedLight: 'text-zinc-500',
    mutedDark: 'text-zinc-400',
    glowColor: 'rgba(24, 24, 27, 0.08)',
    highlightCardBg: '#18181b',
  },
  lavender: {
    id: 'lavender',
    name: 'Morning Lavender',
    tagline: 'Calming lilac mist and soothing wisteria',
    isMonochrome: false,
    isPastel: true,
    previewBg: '#f3e8ff',
    previewAccent: '#9333ea',
    backgroundLight: 'bg-purple-50/70',
    backgroundDark: 'bg-slate-950',
    cardLight: 'bg-white/90',
    cardDark: 'bg-purple-950/40',
    borderLight: 'border-purple-200/80',
    borderDark: 'border-purple-800/40',
    accentLight: 'bg-purple-600 text-white hover:bg-purple-700',
    accentDark: 'bg-purple-400 text-purple-950 hover:bg-purple-300',
    textLight: 'text-purple-950',
    textDark: 'text-purple-100',
    mutedLight: 'text-purple-600/80',
    mutedDark: 'text-purple-300/70',
    glowColor: 'rgba(168, 85, 247, 0.15)',
    highlightCardBg: '#9333ea',
  },
  peach: {
    id: 'peach',
    name: 'Honey Peach',
    tagline: 'Warm soothing peach and morning apricot glow',
    isMonochrome: false,
    isPastel: true,
    previewBg: '#ffedd5',
    previewAccent: '#ea580c',
    backgroundLight: 'bg-orange-50/70',
    backgroundDark: 'bg-stone-950',
    cardLight: 'bg-white/90',
    cardDark: 'bg-orange-950/30',
    borderLight: 'border-orange-200/80',
    borderDark: 'border-orange-800/40',
    accentLight: 'bg-orange-600 text-white hover:bg-orange-700',
    accentDark: 'bg-orange-400 text-orange-950 hover:bg-orange-300',
    textLight: 'text-orange-950',
    textDark: 'text-orange-100',
    mutedLight: 'text-orange-600/80',
    mutedDark: 'text-orange-300/70',
    glowColor: 'rgba(234, 88, 12, 0.15)',
    highlightCardBg: '#ea580c',
  },
  sage: {
    id: 'sage',
    name: 'Sage Blossom',
    tagline: 'Quiet botanical sage and morning dew garden',
    isMonochrome: false,
    isPastel: true,
    previewBg: '#ecfdf5',
    previewAccent: '#059669',
    backgroundLight: 'bg-emerald-50/70',
    backgroundDark: 'bg-zinc-950',
    cardLight: 'bg-white/90',
    cardDark: 'bg-emerald-950/30',
    borderLight: 'border-emerald-200/80',
    borderDark: 'border-emerald-800/40',
    accentLight: 'bg-emerald-700 text-white hover:bg-emerald-800',
    accentDark: 'bg-emerald-400 text-emerald-950 hover:bg-emerald-300',
    textLight: 'text-emerald-950',
    textDark: 'text-emerald-100',
    mutedLight: 'text-emerald-600/80',
    mutedDark: 'text-emerald-300/70',
    glowColor: 'rgba(5, 150, 105, 0.15)',
    highlightCardBg: '#059669',
  },
  rose: {
    id: 'rose',
    name: 'Rosewater Blush',
    tagline: 'Delicate maternal warmth and soft tea rose petal',
    isMonochrome: false,
    isPastel: true,
    previewBg: '#ffe4e6',
    previewAccent: '#e11d48',
    backgroundLight: 'bg-rose-50/70',
    backgroundDark: 'bg-neutral-950',
    cardLight: 'bg-white/90',
    cardDark: 'bg-rose-950/30',
    borderLight: 'border-rose-200/80',
    borderDark: 'border-rose-800/40',
    accentLight: 'bg-rose-600 text-white hover:bg-rose-700',
    accentDark: 'bg-rose-400 text-rose-950 hover:bg-rose-300',
    textLight: 'text-rose-950',
    textDark: 'text-rose-100',
    mutedLight: 'text-rose-600/80',
    mutedDark: 'text-rose-300/70',
    glowColor: 'rgba(225, 29, 72, 0.15)',
    highlightCardBg: '#e11d48',
  },
  sky: {
    id: 'sky',
    name: 'Dawn Powder Sky',
    tagline: 'Serene morning sky and clear tranquil horizons',
    isMonochrome: false,
    isPastel: true,
    previewBg: '#e0f2fe',
    previewAccent: '#0284c7',
    backgroundLight: 'bg-sky-50/70',
    backgroundDark: 'bg-slate-950',
    cardLight: 'bg-white/90',
    cardDark: 'bg-sky-950/30',
    borderLight: 'border-sky-200/80',
    borderDark: 'border-sky-800/40',
    accentLight: 'bg-sky-600 text-white hover:bg-sky-700',
    accentDark: 'bg-sky-400 text-sky-950 hover:bg-sky-300',
    textLight: 'text-sky-950',
    textDark: 'text-sky-100',
    mutedLight: 'text-sky-600/80',
    mutedDark: 'text-sky-300/70',
    glowColor: 'rgba(2, 132, 199, 0.15)',
    highlightCardBg: '#0284c7',
  },
  sunbeam: {
    id: 'sunbeam',
    name: 'Chamomile Buttercup',
    tagline: 'Bright cheerfulness and gentle morning sunlight',
    isMonochrome: false,
    isPastel: true,
    previewBg: '#fef9c3',
    previewAccent: '#ca8a04',
    backgroundLight: 'bg-amber-50/70',
    backgroundDark: 'bg-stone-950',
    cardLight: 'bg-white/90',
    cardDark: 'bg-amber-950/30',
    borderLight: 'border-amber-200/80',
    borderDark: 'border-amber-800/40',
    accentLight: 'bg-amber-600 text-white hover:bg-amber-700',
    accentDark: 'bg-amber-400 text-amber-950 hover:bg-amber-300',
    textLight: 'text-amber-950',
    textDark: 'text-amber-100',
    mutedLight: 'text-amber-600/80',
    mutedDark: 'text-amber-300/70',
    glowColor: 'rgba(202, 138, 4, 0.15)',
    highlightCardBg: '#ca8a04',
  },
};
